"""
Phase 1, Node M (folder M_quantum).

Independently reconstructs unitary quantum dynamics and explicitly tests the Special Rule:
"Do not identify graph eigenvalues with physical energy eigenvalues... require an explicit
correspondence if such a mapping is proposed."

1. Stone's theorem argument (stated, external, standard functional analysis): a strongly
   continuous one-parameter group of UNITARY operators U(t) is generated by a self-adjoint
   operator H via U(t)=exp(-iHt/hbar); this is the mathematical content behind "why" Schrodinger
   dynamics has the form it does, GIVEN that evolution must be unitary (norm-preserving,
   reversible) -- distinguishing it from the heat semigroup (PROVEN in PRF-PRIM/Node C region to
   be a norm-DECREASING contraction, hence NOT unitary, hence NOT a candidate generator under
   Stone's theorem in the same sense).

2. Numerical toy construction: take H := L (the graph Laplacian itself, a real symmetric hence
   self-adjoint operator) as a CANDIDATE toy Hamiltonian for a finite-dimensional quantum system.
   Simulate U(t)=exp(-iLt) numerically, verify unitarity (norm preservation) to machine precision,
   and CONTRAST directly against exp(-tL) (verified in PRF-PRIM to violate the Liouville/volume
   condition, det->0). This makes concrete, on the SAME operator family, the distinction between
   "graph Laplacian eigenvalue lambda_n" and "a candidate physical energy E_n = hbar*lambda_n":
   the correspondence E_n = hbar*lambda_n is a CHOICE (this repository's own construction for the
   toy model), NOT something derived from the graph structure -- exactly the distinction the
   Special Rule requires be kept explicit.
"""
import json, os
import numpy as np
import networkx as nx

REPO = '/home/user/TOEv/independent_toe/'
OUT = REPO + 'phase_1/M_quantum/'
os.makedirs(OUT, exist_ok=True)

with open(REPO + '../graphs/C0/PRF-PRIM/graph_families.json') as f:
    FAMILIES = json.load(f)

def laplacian(adj):
    A = np.array(adj, dtype=float)
    D = np.diag(A.sum(axis=1))
    return D - A

def main():
    results = {}
    for name, fam in FAMILIES.items():
        L = laplacian(fam['adjacency'])
        eigvals, eigvecs = np.linalg.eigh(L)
        t = 1.3  # arbitrary probe time
        # candidate H = L (toy, hbar=1): U(t) = exp(-i H t)
        U_t = eigvecs @ np.diag(np.exp(-1j * eigvals * t)) @ eigvecs.T
        # unitarity check: U^dagger U = I
        unitarity_error = float(np.max(np.abs(U_t.conj().T @ U_t - np.eye(len(eigvals)))))
        # norm preservation on a random state
        rng = np.random.default_rng(0)
        psi0 = rng.normal(size=len(eigvals)) + 1j * rng.normal(size=len(eigvals))
        psi0 /= np.linalg.norm(psi0)
        psi_t = U_t @ psi0
        norm_t = float(np.linalg.norm(psi_t))
        # contrast: heat semigroup norm at the same t (already known non-unitary, contraction)
        Kt = eigvecs @ np.diag(np.exp(-eigvals * t)) @ eigvecs.T
        phi_t = Kt @ psi0
        norm_heat = float(np.linalg.norm(phi_t))

        results[name] = {
            "unitarity_error_||U^dag U - I||_max": unitarity_error,
            "norm_after_unitary_evolution_(should_stay_1.0)": norm_t,
            "norm_after_heat_semigroup_(EXPECTED_to_shrink,_contraction)": norm_heat,
            "eigenvalues_(candidate_'energies'_E_n=hbar*lambda_n,_hbar=1_CHOICE)": [round(float(x), 4) for x in eigvals],
        }

    correspondence_note = (
        "The identification 'E_n = hbar * lambda_n^graph' used above is an EXPLICIT CHOICE made by "
        "this toy construction (H:=L), not a derivation. No independent argument was found or "
        "constructed establishing that a graph Laplacian eigenvalue IS a physical energy without "
        "this choice. Per the Special Rule, this distinction is preserved rather than silently "
        "collapsed: STATUS of the correspondence lambda_n^graph <-> E_n^physical = CANDIDATE (this "
        "repository's construction), not CALCULATED or DERIVED."
    )

    out = {"per_family_results": results, "graph_eigenvalue_vs_physical_energy_correspondence_note": correspondence_note}
    with open(OUT + 'quantum_unitarity_results.json', 'w') as f:
        json.dump(out, f, indent=2)

    print("=== Node M: Quantum (unitarity vs. heat-semigroup contraction, same operator family) ===")
    for name, r in results.items():
        print(f"  {name}: unitarity_err={r['unitarity_error_||U^dag U - I||_max']:.2e}  "
              f"norm(unitary)={r['norm_after_unitary_evolution_(should_stay_1.0)']:.6f}  "
              f"norm(heat)={r['norm_after_heat_semigroup_(EXPECTED_to_shrink,_contraction)']:.6f}")
    print("\n" + correspondence_note)

if __name__ == '__main__':
    main()
